apiVersion: cert-manager.io/v1
kind: ClusterIssuer # I'm using ClusterIssuer here
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: christian.wiedemann@key-tec.de
    privateKeySecretRef:
      name: cert-manager-acme
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
